# TODO syntax checker like neomake/syntastic
# NOTE: neocomplcache/neocomplete/deoplete are managed in plugin.vim

# save with sudo
[[plugins]]
repository = 'sudo.vim'
lazy = 0

# neobundle itself
[[plugins]]
repository = 'Shougo/neobundle.vim'
fetch = 1

# Unite.vim
[[plugins]]
repository = 'Shougo/unite.vim'

# async library
[[plugins]]
repository = 'Shougo/vimproc.vim'
build_commands = 'make'
build = 'make'

# filer
[[plugins]]
repository = 'Shougo/vimfiler'

# tag window
[[plugins]]
repository = 'majutsushi/tagbar'
external_commands = ['ctags']

# awesome git client
[[plugins]]
repository = 'lambdalisue/vim-gita'

# cool status line
[[plugins]]
repository = 'itchyny/lightline.vim'
depends = ['vim-gita']

# visualize indent
[[plugins]]
repository = 'Yggdroot/indentLine'

# human-friendly window selector
[[plugins]]
repository = 't9md/vim-choosewin'

# save and restore cursor position and folding
[[plugins]]
repository = 'vim-scripts/restore_view.vim'

# automatic charcode detector
[[plugins]]
repository = 'banyan/recognize_charcode.vim'

# capslock alternative
[[plugins]]
repository = 'tpope/vim-capslock'

# manage 'surroundings'
[[plugins]]
repository = 'tpope/vim-surround'

# alignment
[[plugins]]
repository = 'junegunn/vim-easy-align'

# undo history
[[plugins]]
repository = 'mbbill/undotree'

# async :make
[[plugins]]
repository = 'benekastah/neomake'

# insert snippet
[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']

# show document in echo area
[[plugins]]
repository = 'Shougo/echodoc.vim'

# show the number of hit words
[[plugins]]
repository = 'osyo-manga/vim-anzu'

# improve diff mode
[[plugins]]
repository = 'lambdalisue/vim-improve-diff'

# improve diff mode with git
[[plugins]]
repository = 'lambdalisue/vim-unified-diff'
external_commands = 'git'

# vimshell
[[plugins]]
repository = 'Shougo/vimshell.vim'

# improve commit message editor
[[plugins]]
repository = 'rhysd/committia.vim'

# comment in/out
[[plugins]]
repository = 'tyru/caw.vim'

# parenthesis completion
[[plugins]]
repository = 'Raimondi/delimitMate'

# highlight nearest tag pair
[[plugins]]
repository = 'Valloric/MatchTagAlways'

# set background color for colorcodes
[[plugins]]
repository = 'gorodinskiy/vim-coloresque'

# [[plugins]]
# repository = 'thinca/vim-quickrun'
# [[plugins]]
# repository = 'dannyob/quickfixstatus'
# [[plugins]]
# repository = 'KazuakiM/vim-qfstatusline'
# depends = 'osyo-manga/shabadou.vim'

# neocomplcache/neocomplete/deoplete extensions {{{
# -----------------------------------------------------------------------------

[[plugins]]
repository = 'Shougo/neoinclude.vim'

[[plugins]]
repository = 'ujihisa/neco-look'
external_commands = 'look'

[[plugins]]
repository = 'Shougo/neco-syntax'

[[plugins]]
repository = 'Shougo/neco-vim'
# }}}

# Unite sources {{{
# -----------------------------------------------------------------------------

# file_mru and directory_mru
[[plugins]]
repository = 'Shougo/neomru.vim'

# history/yank
[[plugins]]
repository = 'Shougo/neoyank.vim'

[[plugins]]
repository = 'hewes/unite-gtags'
external_commands = ['ctags', 'global']

[[plugins]]
repository = 'Shougo/unite-outline'
external_commands = ['ctags']

[[plugins]]
repository = 'tsukkee/unite-tag'
depends = ['Shougo/neoinclude.vim']

[[plugins]]
repository = 'osyo-manga/unite-quickfix'

[[plugins]]
repository = 'tacroe/unite-mark'

[[plugins]]
repository = 'basyura/unite-rails'

[[plugins]]
repository = 'pasela/unite-webcolorname'
# }}}

# syntax/filetype plugins {{{
# -----------------------------------------------------------------------------

[[plugins]]
repository = 'derekwyatt/vim-scala'

[[plugins]]
repository = 'vim-ruby/vim-ruby'

[[plugins]]
repository = 'iTakeshi/matlab.vim'

[[plugins]]
repository = 'iTakeshi/TempoProtocol.vim'

[[plugins]]
repository = 'kchmck/vim-coffee-script'

[[plugins]]
repository = 'vim-scripts/jQuery'

[[plugins]]
repository = 'alunny/pegjs-vim'

[[plugins]]
repository = 'othree/html5.vim'

[[plugins]]
repository = 'hail2u/vim-css3-syntax'

[[plugins]]
repository = 'cakebaker/scss-syntax.vim'

[[plugins]]
repository = 'groenewege/vim-less'

[[plugins]]
repository = 'cespare/vim-toml'
# }}}

# textobj {{{
# -----------------------------------------------------------------------------

[[plugins]]
repository = 'kana/vim-textobj-user'

[[plugins]]
repository = 'kana/vim-textobj-entire'

[[plugins]]
repository = 'kana/vim-textobj-line'

[[plugins]]
repository = 'kana/vim-textobj-syntax'

[[plugins]]
repository = 'kana/vim-textobj-indent'

[[plugins]]
repository = 'kana/vim-textobj-datetime'

[[plugins]]
repository = 'thinca/vim-textobj-comment'

[[plugins]]
repository = 'saihoooooooo/vim-textobj-space'

[[plugins]]
repository = 'kana/vim-textobj-fold'

[[plugins]]
repository = 'kana/vim-textobj-underscore'

[[plugins]]
repository = 'RyanMcG/vim-textobj-dash'

[[plugins]]
repository = 'mattn/vim-textobj-url'

[[plugins]]
repository = 'sgur/vim-textobj-parameter'

[[plugins]]
repository = 'osyo-manga/vim-textobj-multiblock'

[[plugins]]
repository = 'rhysd/vim-textobj-word-column'
# }}}

# operator {{{
# -----------------------------------------------------------------------------

[[plugins]]
repository = 'kana/vim-operator-user'

[[plugins]]
repository = 'kana/vim-operator-replace'

[[plugins]]
repository = 'rhysd/vim-operator-surround'

[[plugins]]
repository = 'haya14busa/vim-operator-flashy'
# }}}

# icons
[[plugins]]
repository = 'ryanoasis/vim-devicons'
