# These plugins are configured separately in plugin.vim
# neobundle.vim, unite.vim, vimproc.vim

# recognize charcode
[[plugins]]
repository = 'banyan/recognize_charcode.vim'

# tag window
[[plugins]]
repository = 'majutsushi/tagbar'

###############################################################################
# Unite sources {{{
###############################################################################

[[plugins]]
repository = 'Shougo/unite-outline'

[[plugins]]
repository = 'Shougo/unite-help'

[[plugins]]
repository = 'osyo-manga/unite-quickfix'

[[plugins]]
repository = 'rhysd/unite-codic.vim'

[[plugins]]
repository = 'pasela/unite-webcolorname'

[[plugins]]
repository = 'tsukkee/unite-tag'

[[plugins]]
repository = 'tacroe/unite-mark'

[[plugins]]
repository = 'lambdalisue/unite-grep-vcs'

[[plugins]]
repository = 'mattn/unite-remotefile'

[[plugins]]
repository = 'basyura/unite-rails'

[[plugins]]
repository = 'hewes/unite-gtags'

[[plugins]]
repository = 'Shougo/unite-session'

[[plugins]]
repository = 'Shougo/neomru.vim'

[[plugins]]
repository = 'Shougo/neoyank.vim'

[[plugins]]
repository = 'Shougo/vimfiler'

[[plugins]]
repository = 'itchyny/lightline.vim'

[[plugins]]
repository = 'Yggdroot/indentLine'

[[plugins]]
repository = 't9md/vim-choosewin'

[[plugins]]
repository = 'lambdalisue/gita'
