"
" Neovim configuration
" Platform: Linux
"
" Acknowledgements
" This configuration is based on lambdalisue's one
" https://github.com/lambdalisue/rook
"

" reset settings when reloading this configuration file
augroup MyAutoCmd " reset autocmd grouped by MyAutoCmd
  autocmd!
augroup END
set all&          " reset all settings

" disable unnecessary default plugins
let g:loaded_gzip              = 1
let g:loaded_tar               = 1
let g:loaded_tarPlugin         = 1
let g:loaded_zip               = 1
let g:loaded_zipPlugin         = 1
let g:loaded_rrhelper          = 1
let g:loaded_2html_plugin      = 1
let g:loaded_vimball           = 1
let g:loaded_vimballPlugin     = 1
let g:loaded_getscript         = 1
let g:loaded_getscriptPlugin   = 1
let g:loaded_netrw             = 1
let g:loaded_netrwPlugin       = 1
let g:loaded_netrwSettings     = 1
let g:loaded_netrwFileHandlers = 1

" use bash
set shell=/bin/bash

" history ':' commands and search patterns as much as possible (max: 10000)
set history=10000

set t_Co=256
set notimeout ttimeout ttimeoutlen=100

" disable ancient features
set noswapfile
set nobackup
set nowritebackup
set noerrorbells
set novisualbell
set t_vb=

" prefer UTF-8
if has('multi_byte')
  if has('vim_starting')
    set encoding=utf-8
  endif
  scriptencoding utf-8
  set fileencodings=ucs-bom,utf-8,euc-jp,iso-2022-jp,cp932,utf-16,utf-16le
  set fileformats=unix,dos,mac
endif

let s:rc_dir = dotfile_util#normpath('rc', 'config') . g:pathsep
call dotfile_util#source(s:rc_dir . 'search.vim')
call dotfile_util#source(s:rc_dir . 'edit.vim')
call dotfile_util#source(s:rc_dir . 'cursor.vim')
call dotfile_util#source(s:rc_dir . 'fold.vim')
call dotfile_util#source(s:rc_dir . 'interface.vim')
call dotfile_util#source(s:rc_dir . 'keymap.vim')
call dotfile_util#source(s:rc_dir . 'macro.vim')
call dotfile_util#source(s:rc_dir . 'plugin.vim')
